version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/Run_Correlations_Yourself"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
